import { groqService } from "./groqService.js";

export const compareCandidates = async (candidateA, candidateB, roleDescription) => {
  const prompt = `
    Compare these two candidates for the following role:
    Role: ${roleDescription}

    Candidate A:
    - Name: ${candidateA.name}
    - Skills: ${candidateA.skillGap?.matchedSkills?.join(", ")}
    - ATS Score: ${candidateA.atsScore}
    - Semantic Match: ${candidateA.semanticScore}
    - Missing Skills: ${candidateA.skillGap?.missingSkills?.join(", ")}

    Candidate B:
    - Name: ${candidateB.name}
    - Skills: ${candidateB.skillGap?.matchedSkills?.join(", ")}
    - ATS Score: ${candidateB.atsScore}
    - Semantic Match: ${candidateB.semanticScore}
    - Missing Skills: ${candidateB.skillGap?.missingSkills?.join(", ")}

    Provide a professional hiring recommendation in JSON format:
    {
      "recommendation": "Candidate Name",
      "reasoning": ["point 1", "point 2"],
      "risks": ["point 1"],
      "comparisonSummary": "brief text"
    }
  `;

  try {
    const response = await groqService(prompt);
    const cleanJson = response.match(/\{[\s\S]*\}/);
    if (cleanJson) {
      return JSON.parse(cleanJson[0]);
    }
    throw new Error("Invalid LLM response for comparison");
  } catch (error) {
    console.error("Comparison Service Error:", error);
    return {
      recommendation: candidateA.semanticScore > candidateB.semanticScore ? candidateA.name : candidateB.name,
      reasoning: ["Based on higher semantic match score"],
      risks: ["Comparison generated by fallback logic"],
      comparisonSummary: "LLM comparison failed, falling back to score-based ranking."
    };
  }
};
